name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  USERNAME: ${{secrets.USERNAME}}
  PASSWORD: ${{secrets.PASSWORD}}
  HOST: ${{secrets.HOST}}
  PORT: ${{secrets.PORT}}
  DB: ${{secrets.DB}}
  SPACES_KEY: ${{secrets.SPACES_KEY}}
  SPACES_SECRET: ${{secrets.SPACES_SECRET}}
  IMAGE_NAME: olshop

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: nulhakim/olshop-proto:latest

  deploy_do:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.SSHKEY }}
          password: ${{ secrets.PASSPHRASE }}
          envs: IMAGE_NAME,SPACES_KEY,SPACES_SECRET,USERNAME,PASSWORD,PORT,HOST,DB,${{ secrets.DOCKERHUB_USERNAME }},${{ secrets.DOCKERHUB_TOKEN }}
          script: |
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} \
            docker container stop $(echo $IMAGE_NAME) \
            docker container rm $(echo $IMAGE_NAME) \
            docker run -d \
            --restart always \
            --name $(echo $IMAGE_NAME) \
            -e SPACES_KEY=$(echo $SPACES_KEY) -e SPACES_SECRET=$(echo $SPACES_SECRET) \ 
            -e USERNAME=$(echo $USERNAME) -e PASSWORD=$(echo $PASSWORD) -e PORT=$(echo $PORT) -e HOST=$(echo $HOST) -e DB=$(echo $DB) \
            -p 3000:3000 nulhakim/olshop-proto:1.0.2